feat(myscripts): Ability to dis-/enable individual scripts
niveK77pur/77configs pull request #6
Opened 2024-12-26 10:26 UTC by niveK77pur

2024-12-26 10:27 UTC, niveK77pur commented
@trueNAHO This here seems to be working just as expected! Any other suggestions in terms of formatting and organizing the code here?

2024-12-26 15:45 UTC, trueNAHO requested changes

2024-12-26 15:45 UTC, trueNAHO commented on nix/myscripts/default.nix
> +    (lib.mkIf cfg.we.enable {home.packages = [(pkgs.callPackage ./we.nix {})];})
> Any other suggestions in terms of formatting and organizing the code here?

Wrap the code at 80 characters and reduce indentation nesting with `lib.singleton`:

```nix
(
  lib.mkIf cfg.<OPTION_1>.enable {
    home.packages = lib.singleton (pkgs.callPackage <FILE_1> {});
  }
)

(
  lib.mkIf cfg.<OPTION_2>.enable {
    home.packages = lib.singleton (
      pkgs.callPackage <FILE_2> {
        inherit pkgs;

        one = 1;
        two = 2;
      }
    );
  }
)
```

2025-04-07 18:02 UTC, niveK77pur commented
Will scratch the suggestions thus far in favor of how I packaged the `hours` package: https://github.com/niveK77pur/77configs/commit/44f1709133ccb3f81fe123902f9d7b49777495de

It will allow me to define the derivations within the module, without having to create a separate file. That way, I can also allow enabling or not each individual script if desired using a simple and local `enable` option.

2025-04-12 23:11 UTC, merged